# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_prospection', '0004_project_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_featured',
            new_name='post_is_featured',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_featured',
            new_name='proj_is_featured',
        ),
    ]
