# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_prospection', '0005_auto_20170906_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_pic', models.ImageField(null=True, upload_to='')),
                ('featured_video_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
