# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_prospection', '0006_homepagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
