# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('space_prospection', '0007_homepagedata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
