# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_prospection', '0008_homepagedata_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageData',
        ),
    ]
