# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 19:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('space_prospection', '0009_delete_homepagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
